### ISSUE TITLE
Problem in travis builds

### ISSUE THREAD

**Issue by prolic** [prooph/psb-enqueue-producer#6]
With --prefer-lowest no problems, but with newest deps, we have this:

```
PHP Fatal error:  Trait 'Enqueue\AmqpTools\DelayStrategyTransportFactoryTrait' not found in /home/travis/build/prooph/psb-enqueue-producer/vendor/enqueue/enqueue/Symfony/RabbitMqAmqpTransportFactory.php on line 14
```

see: https://travis-ci.org/prooph/psb-enqueue-producer/jobs/311391534

any ideas what's going here? @makasim @iainmckay 

If we can get this fixed, I'll make a new 0.3.1 release asap.

**Comment by makasim** [comment]
add `"enqueue/amqp-tools": "^0.7|^0.8"` to `require-dev`.

**Comment by iainmckay** [comment]
Yes, what @makasim suggested. I ran in to this, I'm not sure why I didn't add it to the composer file. Sorry guys, I dropped the ball there.
