### ISSUE TITLE
How to use EnqueueMessageProcessor?

### ISSUE THREAD

**Issue by enumag** [prooph/psb-enqueue-producer#8]
I'm trying to use this package and managed to setup the Producer to send my commands and messages to RabbitMQ.

What I'm not sure is how to setup the `EnqueueMessageProcessor` to consume the messages. I'm guessing I need to add it to my services like this:

```
    Prooph\ServiceBus\Message\Enqueue\EnqueueMessageProcessor:
        tags:
            - { name: 'enqueue.client.processor' }
```

With this the bundle complains that `topicName` is required. But what `topicName` should I use here?

At first I thought it was the string I passed to `EnqueueMessageProducer` as `$commandName` but it doesn't work (no error but message never arrives into `EnqueueMessageProcessor` when running `bin/console enqueue:consume --setup-broker -vvv`). Also it doesn't make sense because from what I figured about Enqueue the `$commandName` string should be used as `processorName` [option](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/message_processor.md#container-tag) in the tag. But that brings me back to what topic should I use?

Can you tell me how you set this up? I'll send a PR with docs once I understand it.

**Comment by makasim** [comment]
You should not use Enqueue Client, it is a high-level abstraction. Instead. you have to use transport directly. Remove tag and use `enqueue:transport:consume` command.

**Comment by enumag** [comment]
> You should not use Enqueue Client, it is a high-level abstraction. Instead. you have to use transport directly.

Out of curiosity, what is the reason why I can't use the high-level abstraction?

Also the abstraction seemed quite useful because of `--setup-broker` - if I understand it correctly it sets up the exchanges, channels and queues as needed without manual configuration, right? I'm not sure how to do it with the low-level command.

---

Anyway the `enqueue:transport:consume` command ends immediately with this error:

```
> bin/console enqueue:transport:consume "Prooph\ServiceBus\Message\Enqueue\EnqueueMessageProcessor"

In ContainerAwareConsumeMessagesCommand.php line 83:

  The queues are not provided. The processor must implement "Enqueue\Consumption\QueueSubscriberInterface" interface and it must return not empty array of queues or queues set using --queue option.                                                                                                                   
```

So I need to add some `--queue=?` parameter to the command - where do I get the queue name?

**Comment by makasim** [comment]
@enumag you could. implement command subscriber interface, use the tag. 

The implementation could look like this https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Queue/PopulateProcessor.php#L127

**Comment by makasim** [comment]
> Anyway the enqueue:transport:consume command ends immediately with this error:

use `--help` to see how to properly configure the command, there is an argument is missing.

**Comment by makasim** [comment]
> So I need to add some --queue=? parameter to the command - where do I get the queue name?

The queue you send message too

**Comment by enumag** [comment]
> The queue you send message too

Well I have no idea what queue that is. Sending the message is handled by `EnqueueMessageProducer` from this package but there is no queue name there.

**Comment by enumag** [comment]
> The implementation could look like this https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Queue/PopulateProcessor.php#L127

The `EnqueueMessageProcessor` in this package is final so I can't add that method to it. Of course I could decorate it but I doubt that's the intended usage - that would have been written in the readme I think.

EDIT: Besides shouldn't it be possible to do the same configuration using symfony tag attributes? At least that's the impression I got from enqueue docs.

**Comment by makasim** [comment]
> to do the same configuration using symfony tag attributes?
Yes, it should be possible

**Comment by enumag** [comment]
> Yes, it should be possible

Well then how? According to docs topicName is required in the tag attributes. But the PopulateProcessor you linked does not have any.

**Comment by enumag** [comment]
It seems I finally got it to work. The solution seems to be this:

```
    Prooph\ServiceBus\Message\Enqueue\EnqueueMessageProducer:
        $commandName: 'my_application'
        $replyTimeout: 1000

    Prooph\ServiceBus\Message\Enqueue\EnqueueMessageProcessor:
        tags:
            - { name: 'enqueue.client.processor', topicName: '__command__', processorName: 'my_application' }
```

Does it look ok to you? Why didn't you tell me that the topic name was supposed to be `__command__`?

**Comment by makasim** [comment]
> Why didn't you tell me that the topic name was supposed to be __command__?

@enumag sorry dude I have other stuff to do. 

FYI: In 0.9 version the configuration is simpler.

```
  - { name: 'enqueue.processor', command: 'my_command' }
```

**Comment by enumag** [comment]
Thanks for the 0.9 tip!

Reopen this issue pls. I indend to close it myself with a pullrequest documenting the solution. If it's closed I might easily forget about it.
